on:
  issues:
    types: [opened]
name: Invite a new user by comment
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: checkout repo content
          uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install requests
            if [ -f ./.github/workflows/requirements.txt ]; then pip install -r ./.github/workflows/requirements.txt; fi
        - name: execute py script
          id: run_script
          run: |
            # Capture Python script output in a variable and grep for "pending" or "active" state
            OUTPUT=$(python ./.github/workflows/AutoInviteToOrgByNewIssue.py)
            echo "$OUTPUT" | grep -E '"?state"?[:=]"?(pending|active)"?'
          env:
            MY_GITHUB_KEY: ${{ secrets.MY_GITHUB_KEY }}
            COMMUNITY_TEAM_ID: ${{ secrets.COMMUNITY_TEAM_ID }}


