on:
  issues:
    types: [opened]
name: Invite a new user by comment
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: checkout repo content
          uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #5.0.0
        - name: setup python
          uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c #6.0.0
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install requests
            if [ -f ./.github/workflows/requirements.txt ]; then pip install -r ./.github/workflows/requirements.txt; fi
        - name: execute py script
          id: run_script
          run: |
            # Capture Python script output in a variable and grep for "pending" or "active" state
            OUTPUT=$(python ./.github/workflows/AutoInviteToOrgByNewIssue.py)
            
            # Only proceed to grep if the output is non-empty
            if [ -n "$OUTPUT" ]; then
              echo "$OUTPUT" | grep -E '"?state"?[:=]"?(pending|active)"?'
            else
              echo "'RaiseHigh' was not found in the issue title "
            fi                     
          env:
            MY_GITHUB_KEY: ${{ secrets.MY_GITHUB_KEY }}
            COMMUNITY_TEAM_ID: ${{ secrets.COMMUNITY_TEAM_ID }}


